package io.dagger.codegen;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.dagger.codegen.introspection.Fixtures;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class GeneratorTest {

  private static final String HELLO = Fixtures.clientSchema("hello", "Hello", "hello", "asHello");
  private static final String BUILDER =
      Fixtures.clientSchema("builder", "Builder", "builder", "asBuilder");

  @TempDir Path dir;

  @Test
  void aPlanEmitsCoreAndOnePackagePerClientIntoOneTree() throws Exception {
    Path plan = plan(Map.of("core", core(HELLO), "client-hello", client(HELLO, "hello")));
    Path out = dir.resolve("out");

    Generator.generate(
        GenerationPlan.read(plan), "v1.0.0-beta.10", out, StandardCharsets.UTF_8, s -> {});

    assertThat(out.resolve("io/dagger/core"))
        .isDirectoryContaining("glob:**/Core.java")
        .isDirectoryContaining("glob:**/Container.java")
        .isDirectoryContaining("glob:**/Binding.java")
        .isDirectoryContaining("glob:**/Version.java")
        .isDirectoryContaining("glob:**/JsonConverter.java")
        .isDirectoryNotContaining("glob:**/Hello.java");
    assertThat(out.resolve("io/dagger/client/hello"))
        .isDirectoryContaining("glob:**/Hello.java")
        .isDirectoryNotContaining("glob:**/Version.java")
        .isDirectoryNotContaining("glob:**/JsonConverter.java")
        .isDirectoryNotContaining("glob:**/Container.java");
    assertThat(Files.readString(out.resolve("io/dagger/client/hello/Hello.java")))
        .startsWith(
            "// This class has been generated by dagger-java-sdk. DO NOT EDIT.\npackage io.dagger.client.hello;")
        .contains("import io.dagger.sdk.Session;")
        .contains("import io.dagger.sdk.ModuleBinding;")
        .contains("public static Hello from(Session dag, String name)");
    assertThat(Files.readString(out.resolve("io/dagger/core/Core.java")))
        .contains("package io.dagger.core;")
        .contains("public static Core from(Session session)")
        .contains("public static Core core(Session session)")
        .contains("new Core(session.queryBuilder())")
        .doesNotContain("hello(")
        .doesNotContain("ModuleBinding")
        .doesNotContain("ensureServed")
        .doesNotContain("Connection");
    // The runtime builds scalars reflectively from another package.
    assertThat(Files.readString(out.resolve("io/dagger/core/ID.java")))
        .contains("public ID(String value)");
  }

  @Test
  void corePackageBytesDoNotDependOnWhichModuleTheSchemaWasBoundTo() throws Exception {
    Path fromHello = dir.resolve("hello");
    Path fromBuilder = dir.resolve("builder");
    Generator.generate(
        GenerationPlan.read(plan(Map.of("core", core(HELLO)))),
        "v1.0.0-beta.10",
        fromHello,
        StandardCharsets.UTF_8,
        s -> {});
    Generator.generate(
        GenerationPlan.read(plan(Map.of("core", core(BUILDER)))),
        "v1.0.0-beta.10",
        fromBuilder,
        StandardCharsets.UTF_8,
        s -> {});
    assertThat(tree(fromHello.resolve("io/dagger/core")))
        .isNotEmpty()
        .isEqualTo(tree(fromBuilder.resolve("io/dagger/core")));
  }

  @Test
  void aFullPlanDropsClientPackagesItDoesNotMentionExceptTheKeptOne() throws Exception {
    Path out = dir.resolve("out");
    Path dropped = out.resolve("io/dagger/client/dropped/Dropped.java");
    Path kept = out.resolve("io/dagger/client/self/Self.java");
    Path staleCore = out.resolve("io/dagger/core/Stale.java");
    Files.createDirectories(dropped.getParent());
    Files.createDirectories(kept.getParent());
    Files.createDirectories(staleCore.getParent());
    Files.writeString(dropped, "a dependency that is no longer declared");
    Files.writeString(kept, "the module's own client from the previous generation");
    Files.writeString(staleCore, "a core type the schema no longer has");

    Generator.generate(
        GenerationPlan.read(
            plan(Map.of("core", core(HELLO), "client-hello", client(HELLO, "hello")))),
        "v1.0.0-beta.10",
        out,
        StandardCharsets.UTF_8,
        "self",
        s -> {});

    assertThat(dropped).doesNotExist();
    assertThat(staleCore).doesNotExist();
    assertThat(kept).exists();
    assertThat(out.resolve("io/dagger/client/hello/Hello.java")).exists();
  }

  @Test
  void aPlanWithoutCoreLeavesEveryOtherClientPackageAlone() throws Exception {
    Path out = dir.resolve("out");
    Path other = out.resolve("io/dagger/client/other/Other.java");
    Files.createDirectories(other.getParent());
    Files.writeString(other, "untouched");

    Generator.generate(
        GenerationPlan.read(plan(Map.of("client-hello", client(HELLO, "hello")))),
        "v1.0.0-beta.10",
        out,
        StandardCharsets.UTF_8,
        s -> {});

    assertThat(other).exists();
    assertThat(out.resolve("io/dagger/client/hello/Hello.java")).exists();
    assertThat(out.resolve("io/dagger/core")).doesNotExist();
  }

  @Test
  void aPlanHoldsAtMostOneCore() throws Exception {
    Path plan = plan(Map.of("a", core(HELLO), "b", core(BUILDER)));
    assertThatThrownBy(
            () ->
                Generator.generate(
                    GenerationPlan.read(plan),
                    "v",
                    dir.resolve("out"),
                    StandardCharsets.UTF_8,
                    s -> {}))
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessageContaining("at most one core");
  }

  @Test
  void twoModulesThatNameTheSamePackageAreRejected() throws Exception {
    Path plan =
        plan(
            Map.of(
                "client-a",
                client(
                    Fixtures.clientSchema("my-module", "MyModule", "myModule", "asMyModule"),
                    "my-module"),
                "client-b",
                client(
                    Fixtures.clientSchema("mymodule", "Mymodule", "mymodule", "asMymodule"),
                    "mymodule")));
    Path out = dir.resolve("out");

    assertThatThrownBy(
            () ->
                Generator.generate(
                    GenerationPlan.read(plan),
                    "v1.0.0-beta.10",
                    out,
                    StandardCharsets.UTF_8,
                    s -> {}))
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessageContaining("my-module")
        .hasMessageContaining("mymodule")
        .hasMessageContaining("io.dagger.client.mymodule");
    assertThat(out).doesNotExist();
  }

  @Test
  void anEntryWithoutItsFilesOrWithAnUnknownModeIsRejected() throws Exception {
    Path incomplete = dir.resolve("incomplete");
    Files.createDirectories(incomplete.resolve("x"));
    Files.writeString(incomplete.resolve("x/schema.json"), HELLO);
    assertThatThrownBy(() -> GenerationPlan.read(incomplete))
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessageContaining("x")
        .hasMessageContaining("meta.json");

    Path odd = plan(Map.of("y", Map.of("schema.json", HELLO, "meta.json", "{\"mode\":\"weird\"}")));
    assertThatThrownBy(() -> GenerationPlan.read(odd))
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessageContaining("weird");
  }

  @Test
  void clientPackagesAreNamedAfterTheModule() {
    assertThat(Generator.clientPackage("hello")).isEqualTo("io.dagger.client.hello");
    assertThat(Generator.clientPackage("my-module")).isEqualTo("io.dagger.client.mymodule");
  }

  private static Map<String, String> core(String schema) {
    return Map.of("schema.json", schema, "meta.json", "{\"mode\":\"core\"}");
  }

  private static Map<String, String> client(String schema, String module) {
    return Map.of(
        "schema.json",
        schema,
        "meta.json",
        "{\"mode\":\"client\",\"module\":\""
            + module
            + "\",\"binding\":{\"kind\":\"LOCAL_SOURCE\",\"ref\":\"dagger/modules/"
            + module
            + "\",\"pin\":\"\"}}");
  }

  private Path plan(Map<String, Map<String, String>> entries) throws IOException {
    Path plan = Files.createTempDirectory(dir, "plan");
    for (Map.Entry<String, Map<String, String>> entry : entries.entrySet()) {
      Path entryDir = Files.createDirectories(plan.resolve(entry.getKey()));
      for (Map.Entry<String, String> file : entry.getValue().entrySet()) {
        Files.writeString(entryDir.resolve(file.getKey()), file.getValue());
      }
    }
    return plan;
  }

  /** Relative path to content, for every file under a root. */
  private static Map<String, String> tree(Path root) throws IOException {
    Map<String, String> tree = new HashMap<>();
    try (Stream<Path> files = Files.walk(root)) {
      for (Path file : files.filter(Files::isRegularFile).toList()) {
        tree.put(root.relativize(file).toString(), Files.readString(file));
      }
    }
    return tree;
  }
}
