package io.dagger.codegen.introspection;

import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Path;

public class CodeWriter {
  private final String targetPackage;
  private final Charset encoding;
  private final Path targetDirectory;

  public CodeWriter(String targetPackage, Path targetDirectory, Charset encoding) {
    this.targetPackage = targetPackage;
    this.encoding = encoding;
    this.targetDirectory = targetDirectory;
  }

  public void write(TypeSpec typeSpec) throws IOException {
    JavaFile javaFile =
        JavaFile.builder(targetPackage, typeSpec)
            .addFileComment("This class has been generated by dagger-java-sdk. DO NOT EDIT.")
            .indent("    ")
            .build();
    javaFile.writeTo(targetDirectory, encoding);
  }
}
